# Detects monitor geometry (physical pixels, virtual-desktop coordinates) and writes
# config/monitors.local.js, which the page and the exporter both prefer over the
# hard-coded rects in config/atlas.config.js.
#
#   powershell -ExecutionPolicy Bypass -File tools/detect-monitors.ps1 [-Site home]
param([string]$Site = "home")

Add-Type @"
using System; using System.Runtime.InteropServices;
public static class Dpi { [DllImport("user32.dll")] public static extern bool SetProcessDPIAware(); }
"@
[void][Dpi]::SetProcessDPIAware()
Add-Type -AssemblyName System.Windows.Forms

$screens = [System.Windows.Forms.Screen]::AllScreens | Sort-Object { $_.Bounds.X }
$list = @()
foreach ($s in $screens) {
  $list += [ordered]@{ device = $s.DeviceName; x = $s.Bounds.X; y = $s.Bounds.Y; w = $s.Bounds.Width; h = $s.Bounds.Height; primary = $s.Primary }
}
$json = ($list | ConvertTo-Json -Compress)
if ($list.Count -eq 1) { $json = "[$json]" }
$out = Join-Path $PSScriptRoot "..\config\monitors.local.js"
$body = "// Generated by tools/detect-monitors.ps1 on $(Get-Date -Format s). Do not edit; re-run to refresh.`n" +
        "(function(g){ (g.ATLAS_MONITORS = g.ATLAS_MONITORS || {})[$([string]::Format('"{0}"', $Site))] = $json; })(typeof window !== 'undefined' ? window : globalThis);`n"
[System.IO.File]::WriteAllText((Resolve-Path (Split-Path $out)).Path + "\monitors.local.js", $body, (New-Object System.Text.UTF8Encoding $false))
Write-Host "wrote config/monitors.local.js:"; Write-Host $json
